### ISSUE TITLE
fix combat engagement when hitting certain entities

### ISSUE THREAD

**Issue by myavuzokumus** [lokka30/PhantomCombat#34]
When left click ITEM_FRAME and started attacked mode.
Can you fix this?
Or you can add
> disable-entitys:
> - ITEM_FRAME
> - ARMOR_STAND

this settings?

**Comment by lokka30** [comment]
added 'blacklisted mobs' to the combat mode settings, now you won't be engaged in combat when breaking item frames, etc.
Added in upcoming release, needs testing however.

**Comment by lokka30** [comment]
Testing complete
Sent an update on spigot now :)
